config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    get 'like_it' => "posts#like"
    get 'comment_it' => "posts#add_comment"
  end
  resources :comments do
    get 'reply' => "comments#render_reply_form"
    post 'send_reply' => "comments#reply"
  end

  get 'search_posts' => "posts#render_search_popup"

  root 'pages#front'

  resources :users
  resources :sessions
  delete 'logout' => 'sessions#destroy'

  namespace :api do
    namespace :v1 do
      resources :posts, only: [:index, :show]
      resources :users, only: [:index, :show]
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  has_ancestry
  
  validates_presence_of :body, :author, :post

  belongs_to :post
  belongs_to :author, class_name: "User", foreign_key: "user_id"

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
  acts_as_votable

  validates :title, length: { in: 5..100 }, uniqueness: true
  validates :body, presence: true

  belongs_to :author, class_name: "User", foreign_key: "user_id"

  has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :email, :name
  validates_uniqueness_of :email, :name
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, length: { in: 2..15 }

  has_many :posts
  has_many :comments
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController

  def index
    @posts = Post.all
    render json: @posts
  end

  def show
  	@post = Post.find(params[:id])
  	render json: @post
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  def index
    users = User.all
    render json: users
  end

  def show
    user = User.find(params[:id])
    render(json: Api::V1::UserSerializer.new(user).to_json)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def require_authenticate
    redirect_to new_session_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :require_authenticate, except: [:show]
  before_action :check_ownership, only: [:edit]

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    respond_to do |format|
      if @comment.save
        format.js
      else
        # do nothing
      end
    end
    
  end

  def render_reply_form
    @comment = Comment.find(params[:comment_id])
    @post = Post.find(params[:post_id])
  end

  def reply
    @comment = Comment.find(params[:comment_id])
    @reply = @comment.children.new(comment_params)
    @reply.author = current_user
    @reply.post = Post.find(params[:post_id])

    @reply.save
  end

# def update
#    respond_to do |format|
#      if @comment.update(post_params)
#        format.html { redirect_to @comment, notice: 'Post was successfully updated.' }
#        format.json { render :show, status: :ok, location: @comment }
#     else
#        format.html { render :edit }
#       format.json { render json: @comment.errors, status: :unprocessable_entity }
#     end
#    end
#  end

  def destroy
    respond_to do |format|
      if @comment.destroy
        format.js
      else
        # do nothing
      end
    end
  end

#  def like
#    @comment = Comment.find(params[:post_id])
#    @user = current_user
#    @comment.liked_by @user
# end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

  def check_ownership
    redirect_to root_path unless @comment.author == current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
    @posts = Post.order("created_at DESC")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_authenticate, except: [:show]
  before_action :check_ownership, only: [:edit]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  def show
    @comments = @post.comments.roots.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    tags = params[:tags]
    @post.tag_list.add(tags, parse: true)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    tags = params[:tags]
    @post.tag_list.add(tags, parse: true)
    
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def render_search_popup
  end

  def like
    @post = Post.find(params[:post_id])
    @user = current_user
    @post.liked_by @user
  end


  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, :tag_list, :user_id)
  end

  def check_ownership
    redirect_to root_path unless @post.author == current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You're in!"
    else
      flash.now.alert = "Email or password is invalid!"
      render "new"
    end
  end

  def destroy
    reset_session
    redirect_to :back
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :check_ownership, only: [:show]

  def new
    @user = User.new    
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "You're in!"
    else
      flash.now.alert = "Re-check da fields!"
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end 

  def set_user
    @user = User.find(params[:id])
  end

  def check_ownership
    redirect_to root_path unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>" class="un-comment-row">
  <div class="un-comment-avatar"><!--
    <img src="img/media/avatars/img1.jpg" alt="">-->
  </div>
                  
  <div class="un-comment-cloud">
    <div class="un-comment-arrow"></div>
    <div class="un-btn-reply">
      <%= link_to comment_reply_path(comment, post_id: @post), remote: true do %>
        <i class="fa fa-reply"></i>
      <% end %>
    </div>
    <div class="un-comment-author"><%= link_to comment.author.name, comment.author %></div>
    <div class="un-comment-date">
      <%= comment.created_at %> | 
      <%= link_to comment_path(comment), method: :delete, remote: true do %>
        remove <i class="fa fa-times"></i>
      <% end if comment.author == current_user %>
    </div>
    <div class="un-comment"><%= comment.body %></div>
  </div>

  <ul class="un-comment-list-reply">
    <% comment.descendants.limit(5).each do |cc| %>
    <li id="comment-<%= cc.id %>" class="un-comment-row">
      <div class="un-comment-avatar"><!--
        <img src="img/media/avatars/img1.jpg" alt="">-->
      </div>
      <div class="un-comment-cloud">
        <div class="un-comment-arrow"></div>
        <div class="un-btn-reply">
          <%= link_to comment_reply_path(cc, post_id: @post), remote: true do %>
            <i class="fa fa-reply"></i>
          <% end %>
        </div>
        <div class="un-comment-author"><%= link_to cc.author.name, cc.author %></div>
        <div class="un-comment-date">
        <%= cc.created_at %> | 
        <%= link_to comment_path(cc), method: :delete, remote: true do %>
          remove <i class="fa fa-times"></i>
        <% end if cc.author == current_user %>
        </div>
        <div class="un-comment"><span style="font-weight:bold;">To <%= cc.parent.author.name %>: </span><%= cc.body %></div>
      </div>
    </li>
    <% end %>
  </ul>

</li><!-- end first comment -->

app/views/comments/_reply_form.html.erb
<li class="reply-form" style="padding-bottom: 20px;">
<%= form_for Comment.new, url: comment_send_reply_path(comment), remote: true do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :post_id, post_id %>
  <div class="field">
    <%= f.text_area :body, class: "un-input" %>
  </div>
  <%= f.submit class: "un-btn-submit" do %>
    post comment <i class="un-icon-feather"></i>
  <% end %>
<% end %>
</li>

app/views/comments/create.js.erb
$("#comments-container").prepend("<%= escape_javascript(render :partial => @comment, :locals => {:comment => @comment}) %>");

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/comments/render_reply_form.js.erb
$(".reply-form").remove();
$("#comment-<%= @comment.id %> .un-comment-cloud").append("<%= j render(partial: 'reply_form', locals: { post_id: @post.id, comment: @comment }) %>");

app/views/comments/reply.js.erb
$(".reply-form").remove();
$("#comment-<%= @comment.id %>").html("<%= j render(partial: @comment, locals: {comment: @comment}) %>");

app/views/layouts/_body.html.erb
  <div class="un-grid-post">
    <%= render @posts %>
  </div>                        


app/views/layouts/_footer.html.erb
    <footer class="un-footer">
        <div class="un-container">
            <div class="un-btn-top">
                <i class="un-icon-keyboard-arrow-up"></i>
            </div>
            <div class="un-logo-footer">
                <span class="un-logo-sticky"><a href="#"><span>news</span>able</a></span>
            </div>
            <div class="un-copy">© 2016 <a href="#">Miller</a> Team - All Rights Reserved</div>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<header class="un-header-wide un-shadow">
  <div class="un-menu-device">
  	<div class="un-container">
          <div class="un-logo-left un-logo-device un-pull-left">
              <a href="<%= root_path %>"><div><%= current_user ? current_user.name : "newsables"  %></div></a>
          </div>
          <div class="un-btn-switch un-pull-right">
              <i class="un-icon-menu"></i>
          </div>
      </div>
  </div>
  <div class="un-menu-wide">
  	<nav class="un-menu-left un-pull-left">
      <ul class="un-main-menu">
      	<li class="un-item-parent"><a href="<%= new_post_path %>">add post<i class="un-icon-keyboard-arrow-right"></i></a></li>
      </ul>
    </nav>
    <div class="un-logo-center">
    	<span class="un-logo-sticky"><a href="<%= root_path %>"><div><%= current_user ? current_user.name : "newsables" %></div></a></span>
    </div>
    <nav class="un-menu-right un-menu-wide un-pull-right">
      <ul class="un-main-menu">          	
        <% if current_user %>
          <li class="un-item-parent">
          <%= link_to user_path(current_user) do %>
            admin<i class="un-icon-keyboard-arrow-right"></i> 
          <% end %>
          </li>
          <li class="un-item-parent">
          <%= link_to logout_path, method: :delete do %>
             Log out<i class="fa fa-power-off" style="font-size: 13px;line-height: 14px;"></i> 
          <% end %>
          </li>
        <% else %>
          <li class="un-item-parent">
          <%= link_to "Sign In", new_session_path %>
          </li>
        <% end %>
      </ul>
    </nav>
    <div class="un-clearfix"></div>  
  </div>

  <div class="un-share-center">
  	<ul class="un-list-share-top un-list-share">
          <li id="up-btn-search">
          <%= link_to search_posts_path, remote: true do %>
            <i class="un-icon-search"></i>
          <% end %>
          </li>
          <li><a target="_blank" href="https://twitter.com"><i class="un-icon-social-twitter"></i></a></li>
          <li><a target="_blank" href="https://facebook.com"><i class="un-icon-facebook"></i></a></li>
          <li><a target="_blank" href="http://www.google.com/"><i class="un-icon-google-plus"></i></a></li>
          <li><a target="_blank" href="https://instagram.com/"><i class="un-icon-instagram"></i></a></li>
          <li><a target="_blank" href="https://it.pinterest.com/"><i class="un-icon-pinterest"></i></a></li>
      </ul>  
  </div>
  <% render 'layouts/messages' %>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsable</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <link href="/assets/css/skin.less" rel="stylesheet/less" >
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <script src="/assets/js/less.min.js"></script>
    <%= csrf_meta_tags %>
</head>
<body>

  <div id="un-wrap">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/pages/front.html.erb
<div class="un-page-blog un-page-full">
    <div class="un-container un-content">
        <%= render 'layouts/body' %>
        <div class="un-clearfix"></div>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <br />
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, id: "froala-editor" %>
  </div>
  <br />
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <br />
  <div class="field">
    <%= label_tag :tags %><br>
    <%= text_field_tag :tags %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

  <!-- Initialize the editor. -->
<script>
  $(function() {
    $('#froala-editor').froalaEditor({
      toolbarButtons: ['undo', 'redo', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontSize', 'paragraphStyle', 'paragraphFormat', 'align', 'outdent', 'indent', 'clearFormatting', 'selectAll', 'html']
    })
  });
</script>

app/views/posts/_modal_search_form.html.erb
<div id="un-search-modal" class="un-search-modal">
	<div class="un-search-close"><i class="un-icon-close"></i></div>
	<%= search_form_for query, id: "un-search-form", class: "un-search-form" do |f| %>
	  <%= f.search_field :title_or_body_cont, id: "un-search-field", class: "un-search-field", placeholder: "type here" %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="un-col-md-4 un-col-grid">
  <div class="un-item-post un-item-grid">
    <div class="un-post-media un-post-image">
      <img src="<%= post.image %>" alt="">
      <div class="un-item-overlay-1"></div>
      <div class="un-item-more-icon"><i class="un-icon-read-more"></i><div></div></div>
    </div><!-- end post top / slider -->
    <div class="un-post-caption un-shadow">
      <div class="un-post-head">
        <div class="un-post-hash">
          <% post.tag_list.each do |tag| %>
          <span style="text-transform: lowercase;">#<%= tag %></span>
          <% end %>
        </div>
        <div class="un-post-title"><%= link_to post.title, post_path(post) %></div>
      </div>
      <div class="un-post-exc">
        <%= truncate(post.body, :ommision => "... Read More", :length => 100) %>
      </div>
      <div class="un-post-info">
        <div class="un-post-meta un-pull-left">
          <span class="un-post-date">by <%= post.author.name %></span>
        </div>
        <div class="un-post-stats un-pull-right">
          <% if post.author == current_user %>
          <span class="un-post-views"><i class="fa fa-cogs"></i><%= link_to "edit", edit_post_path(post) %></span>
          <% end %>
          <span class="un-post-views">
            <%= link_to post_like_it_path(post), remote: true do %>
            <i class="fa fa-heart-o"></i>
            <% end %>
            <%= post.votes_for.size %>
          </span>
        </div>
        <div class="un-clearfix"></div>
      </div><!-- end post meta / stats -->
    </div><!-- end post caption -->
  </div><!-- end item post image -->
</div>

app/views/posts/edit.html.erb
<div class="un-page-standard un-page-sidebar">
  <div class="un-container">
    <div class="un-col-md-8 un-content">
      <div class="un-item-post un-item-medium">
        <%= render 'form' %>
        <br />
        <%= link_to 'Back', posts_path %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="un-page-blog un-page-full">
    <div class="un-container un-content">
        <%= render 'layouts/body' %>
        <div class="un-clearfix"></div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="un-page-standard un-page-sidebar">
  <div class="un-container">
    <div class="un-col-md-8 un-content">
  		<div class="un-item-post un-item-medium">
  			<%= render 'form' %>
        <br />
  			<%= link_to 'Back', posts_path %>
  		</div>
    </div>
  </div>
</div>

app/views/posts/render_search_popup.js.erb
$('body').append("<%= j (render 'posts/modal_search_form', query: Post.ransack(params[:q])) %>");

TweenMax.set( $('body'), { overflow: "hidden" } );		

TweenMax.to( $('#un-search-modal'), 0.1, { left: "0",  ease:Power2.easeOut } );
TweenMax.to( $('.un-search-row'), 0.1, { width: "100%",  ease:Power2.easeOut, delay:0.1 } );


$('.un-search-close').on( 'click', function(){
	TweenMax.set( $('body'), { overflow: "" } );
	TweenMax.to( $('.un-search-row'), 0.1, { width: "0",  ease:Power2.easeOut } );
	TweenMax.to( $('#un-search-modal'), 0.1, { left: "100%",  ease:Power2.easeOut, delay:0.1 } );	
	
	setTimeout(function(){
		$('#un-search-modal').remove();
	}, 1500);
		
});

app/views/posts/show.html.erb
<div class="un-page-standard un-page-sidebar">
  <div class="un-container">
    <div class="un-col-md-8 un-content">
  		<div class="un-item-post un-item-medium">

  			<div class="un-post-media un-post-image un-overlay-4">
  			  <%= image_tag(@post.image) %>
        </div><!-- end page top / page media -->

  			<div class="un-post-caption un-shadow">

  				<div class="un-share-mask"></div>
  				
  			    <ul class="un-list-share un-list-share-side">
  			    	<li><a href="#"><i class="un-icon-social-twitter"></i></a></li>
  			        <li><a href="#"><i class="un-icon-facebook"></i></a></li>
  			        <li><a href="#"><i class="un-icon-google-plus"></i></a></li>
  			        <li><a href="#"><i class="un-icon-pinterest"></i></a></li>
  			    </ul>

  				  <div class="un-post-head">
              <div class="un-post-hash">
                <% @post.tag_list.each do |tag| %>
                <span style="text-transform: lowercase;">#<%= tag %></span>
                <% end %>
              </div>
              <div class="un-post-title"><%= @post.title %></div>
              <div class="un-divider-center"></div>
  			    </div>
  			    
  			    <div class="un-post-content">
              <%= @post.body.html_safe %>
            </div>
  			                        
  			    <div class="un-post-info">
  			        <div class="un-post-stats un-pull-right">
                  <% if @post.author == current_user %>
  			        	<span class="un-post-views"><i class="fa fa-cogs"></i><%= link_to "edit", edit_post_path(@post) %></span>
                  <% end %>
                  <span class="un-post-views"><i class="un-icon-eye"></i>575</span>
  			        </div>
  			        <div class="un-clearfix"></div>
  			    </div><!-- end page meta / stats -->
  			            
  			</div><!-- end page content -->



  		</div>

<!-- comments -->

<div class="un-comments">
  <div class="un-comments-title"><%= @post.comments.count %> comments</div>
  <ul id="comments-container" class="un-comment-list">
    <%= render @comments %>
  </ul><!-- end comment list -->
</div>

<!-- // comments -->

<!-- comment form -->
<div class="un-comment-form">

  <div id="comments-form-title" class="un-form-title">leave a reply</div>
    
  <%= form_for Comment.new, remote: true do |f| %>

    <div class="field">
      <%= f.text_area :body, class: "un-input" %>
    </div>
    <%= f.hidden_field :post_id, value: @post.id %> 
    <%= f.hidden_field :reply_to, id: "reply-to", value: "" %> 
              
    <%= f.submit class: "un-btn-submit" do %>
      post comment <i class="un-icon-feather"></i>
    <% end %>
  
  <% end %>

</div>
<!-- // comment form -->

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="un-page-home un-home-vertical un-social-full">
    <div class="un-home">
      <%= form_for @user do |f| %>
          <% if @user.errors.any? %>
              <div class="error_messages">
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.text_field :email %>
          </div>
          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password %>
          </div>
          <div class="actions"><%= f.submit "Sign Up" %></div>
      <% end %>
        <div class="un-clearfix"></div>
    </div>
</div>

app/views/users/show.html.erb
<center>
<h1><%= @user.name %> is watching you!</h1>
</center>